// @flow
export const GET_LOGIN_VERIFICATION = 'GET_LOGIN_VERIFICATION';
export const GET_LOGIN_VERIFICATION_SUCCESS = 'GET_LOGIN_VERIFICATION_SUCCESS';
export const GET_LOGIN_VERIFICATION_FAILURE = 'GET_LOGIN_VERIFICATION_FAILURE';

export const PLAYER_REGISTRATION = 'PLAYER_REGISTRATION';
export const PLAYER_REGISTRATION_SUCCESS = 'PLAYER_REGISTRATION_SUCCESS';
export const PLAYER_REGISTRATION_FAILURE = 'PLAYER_REGISTRATION_FAILURE';

export const RESET_PLAYER_REGISTRATION_DATA = 'RESET_PLAYER_REGISTRATION_DATA';
